
[build]
YARN_VERSION = "1.22.19"
command = "cd ../.. && yarn install && yarn build --filter=chat..."
NETLIFY_USE_YARN = true
environment = { NODE_VERSION = "16.13.0" }
[[plugins]]
package = "@netlify/plugin-nextjs"
